### ISSUE TITLE
user stories erstellen

### ISSUE THREAD

**Issue by meandor** [Eltonno/SuccessAnalyzer#10]
rollen: administrator, user

**Comment by meandor** [comment]
folien folgen von lion

**Comment by diddyhsv** [comment]
- Als Benutzer/Hochschule kann ich sehen, wieviele und welche meiner Studenten ihr Studium wohl erfolgreich oder eher nicht erfolgreich beenden werden.

- Ganz ehrlich, mehr kann man mit unserem Produkt nicht machen.

**Comment by mattx7** [comment]
- Als Benutzer kann ich neue Daten aus einer lokalen Datei importieren.
- Als Benutzer kann ich mir die Ergebnisse anzeigen lassen. [EPIC]
