### ISSUE TITLE
Make concept for relevant data

### ISSUE THREAD

**Issue by meandor** [Eltonno/SuccessAnalyzer#5]
* Which data is relevant?
 * Total Credit Points
 * Classes - passed or failed?
 * Profs
 * Semester count
 * Distance to university from home
 * Nationality
 * Age
 * ...
* Where can we get the data
 * Unlikely to get real data. Will probably have to invent our own data.

* How much data do we need?
 * Data of at least 30 students that left the university.
 * Data of at least 5 students from each semester that are still studying.

* What and how many classes of Student potencials do we have?
 * 2 - Likely to graduate; not likely to graduate
or
 * 3 - As above + too close to call

* What are our [KPI](https://en.wikipedia.org/wiki/Performance_indicator)s?
 * Subjects passed and failed
 * Total CP

**Comment by diddyhsv** [comment]
Hab die Antworten einfach oben in den Text reingeschrieben
